### ISSUE TITLE
expect(find("input[name=name]").value).to be_empty

### ISSUE THREAD

**Issue by jasterix** [learn-co-curriculum/validations-with-form_tag-rails#10] opened 2019-05-22 21:31 UTC
should be: expect(find("input[name=name]").value).to be_nil

**Comment by drakeltheryuujin** [comment] 2019-09-23 19:24
Hi @jasterix,

This issue appears to be in the wrong location, so I will close it for now. I'm assuming this should be for the lab, not the README, however, this test does not work with the current solution of the lab. If you can open the issue in the correct location and provide additional details as to what the issue is and how this would address the issue, that would be helpful. Thanks for contributing!

**Closed as completed by drakeltheryuujin** 2019-09-23 19:24 UTC
